apiVersion: v1
kind: PersistentVolume
metadata:
  name: syslog-ng-logs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.10.200
    path: /mnt/ghostdata/ghostsilo/99_System/K8S-Data/syslog-ng
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syslog-ng-logs-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: syslog-ng-logs-pv
  resources:
    requests:
      storage: 10Gi
