apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: readarr-ingress
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod-cf"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - readarr.560384.xyz
      secretName: readarr-tls-secret
  rules:
    - host: readarr.560384.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: readarr-svc
                port:
                  number: 80
