authentik:


  error_reporting:
    enabled: false



server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - auth.560384.xyz
    tls:
      - hosts:
          - auth.560384.xyz
        secretName: auth-560384-xyz-tls
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod-cf

postgresql:
  enabled: true
  auth:

