apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kavita-ingress
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod-cf
spec:
  ingressClassName: traefik
  tls:
    - hosts: [kavita.560384.xyz]
      secretName: kavita-tls-secret
  rules:
    - host: kavita.560384.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kavita-svc
                port:
                  number: 80
